[project]
name = "blackmagic"
version = "0.1.0"
description = "A pre-commit wrapper that handles python magic to work with black"
requires-python = ">=3.8"
dependencies = [
    "black==24.3.0"
]

[project.scripts]
blackmagic = "blackmagic.runner:main"
